### ISSUE TITLE
POSIX compatibility

### ISSUE THREAD

**Issue by Pesa** [named-data-iot/ndn-iot-package-over-posix#5]
This package is targeted at "POSIX compatible OS". However, looking at the code, I noticed several incompatibilities with POSIX. These are a couple of examples I saw so far, but I only took a quick look and there may be others:

https://github.com/named-data-iot/ndn-iot-package-over-posix/blob/4b31168c50f67f66243baec7eaf1fb1833744a0b/adaptation/udp/udp-face.c#L203-L204

`MSG_DONTWAIT` is not specified by POSIX.

https://github.com/named-data-iot/ndn-iot-package-over-posix/blob/4b31168c50f67f66243baec7eaf1fb1833744a0b/adaptation/udp/udp-face.c#L208

POSIX.1-2001 allows either `EAGAIN` or `EWOULDBLOCK` to be returned for this case, and does not guarantee that these constants have the same value, so a portable application should check for both.

https://github.com/named-data-iot/ndn-iot-package-over-posix/blob/4b31168c50f67f66243baec7eaf1fb1833744a0b/adaptation/udp/udp-face.c#L58

`FIONBIO` is non-standard. You should use `fcntl(...O_NONBLOCK...)` instead.

**Comment by zjkmxy** [comment]
Fixed. Thank you for your comments!

**Comment by Pesa** [comment]
Well... there are several more instances of these or similar problems still present in the codebase... how do you plan to address them? The 3 cases I reported above were just a few examples I noticed from a quick look.

**Comment by zjkmxy** [comment]
We are planning to review our design recently. I will figure it out then.

**Comment by Pesa** [comment]
Any updates?

**Comment by zjkmxy** [comment]
No. Till now we haven't figured out what else is not compatible to POSIX.

**Comment by yoursunny** [comment]
Is there a linter that automatically find non POSIX complaint function calls?
